// vue/src/App.vue
<script setup>
import { ref, onMounted, onUnmounted } from 'vue'
import ProgressBar from './components/ProgressBar.vue'

const PLACEHOLDER_TEXT =
  'The tower is 324 metres (1,063 ft) tall, about the same height as an 81-storey building, and the tallest structure in Paris. Its base is square, measuring 125 metres (410 ft) on each side. During its construction, the Eiffel Tower surpassed the Washington Monument to become the tallest man-made structure in the world, a title it held for 41 years until the Chrysler Building in New York City was finished in 1930.'

const LOADING_MESSAGE = 'Loading models... (only run once)'
const INPUT_ROWS = 6
const OUTPUT_ROWS = 3

const ready = ref(null)
const disabled = ref(false)
const progressItems = ref([])
const input = ref(PLACEHOLDER_TEXT)
const output = ref('')
const worker = ref(null)

onMounted(() => {
  worker.value ??= new Worker(new URL('./worker.js', import.meta.url), {
    type: 'module',
  })

  /**
   * Handles messages received from the Web Worker
   * @param {MessageEvent} event - The message event from the worker
   */
  const onMessageReceived = (event) => {
    switch (event.data.status) {
      case 'initiate':
        ready.value = false
        progressItems.value = [...progressItems.value, event.data]
        break

      case 'progress':
        progressItems.value = progressItems.value.map((item) => {
          if (item.file === event.data.file) {
            return { ...item, progress: event.data.progress }
          }
          return item
        })
        break

      case 'done':
        progressItems.value = progressItems.value.filter((item) => item.file !== event.data.file)
        break

      case 'ready':
        ready.value = true
        break

      case 'update':
        output.value += event.data.output
        break

      case 'complete':
        disabled.value = false
        break
    }
  }

  worker.value.addEventListener('message', onMessageReceived)

  onUnmounted(() => worker.value?.removeEventListener('message', onMessageReceived))
})

const summarize = () => {
  disabled.value = true
  output.value = ''
  worker.value.postMessage({
    text: input.value,
  })
}
</script>

<template>
  <div class="app">
    <h1>Transformers.js</h1>
    <h2>ML-powered text summarization in Vue!</h2>
    <h3>
      Using
      <a href="https://huggingface.co/Xenova/distilbart-cnn-6-6" target="_blank" class="model-link"
        >Xenova/distilbart-cnn-6-6</a
      >
    </h3>

    <div class="container">
      <div class="textbox-container">
        <textarea
          v-model="input"
          :rows="INPUT_ROWS"
          placeholder="Enter text to summarize..."
        ></textarea>
        <textarea
          :value="output"
          :rows="OUTPUT_ROWS"
          readonly
          placeholder="Summary will appear here..."
        ></textarea>
      </div>
    </div>

    <button :disabled="disabled" @click="summarize">Summarize</button>

    <div class="progress-bars-container">
      <label v-if="ready === false">{{ LOADING_MESSAGE }}</label>
      <div v-for="data in progressItems" :key="data.file">
        <ProgressBar :text="data.file" :percentage="data.progress" />
      </div>
    </div>

    <div class="disclaimer">
      <small
        >⚠️ Disclaimer: AI-generated summaries may be inaccurate or incomplete. Always verify
        important information.</small
      >
    </div>
  </div>
</template>

<style scoped>
.app {
  font-family: Arial, Helvetica, sans-serif;
  max-width: 800px;
  margin: 40px auto;
  padding: 0 20px;
  text-align: center;
}

.container {
  margin: 20px 0;
}

.textbox-container {
  display: flex;
  flex-direction: column;
  gap: 20px;
  margin-bottom: 20px;
}

textarea {
  width: 100%;
  padding: 12px;
  border: 2px solid #ccc;
  border-radius: 8px;
  font-size: 16px;
  font-family: inherit;
  resize: vertical;
  box-sizing: border-box;
}

textarea:focus {
  outline: none;
  border-color: #4caf50;
}

button {
  background-color: #4caf50;
  color: white;
  border: none;
  padding: 12px 24px;
  font-size: 16px;
  border-radius: 8px;
  cursor: pointer;
  transition: background-color 0.3s;
}

button:hover:not(:disabled) {
  background-color: #45a049;
}

button:disabled {
  background-color: #cccccc;
  cursor: not-allowed;
}

.progress-bars-container {
  margin-top: 20px;
}

.progress-bars-container label {
  display: block;
  margin-bottom: 10px;
  font-weight: bold;
}

.disclaimer {
  margin-top: 30px;
  text-align: center;
  color: #666;
  max-width: 600px;
  margin-left: auto;
  margin-right: auto;
}

.model-link {
  color: #2196f3;
  text-decoration: none;
  font-weight: 500;
}

.model-link:hover {
  text-decoration: underline;
}
</style>

// speecht5-web/src/App.jsx
import { useState, useEffect, useRef } from "react";

import AudioPlayer from "./components/AudioPlayer";
import Progress from "./components/Progress";
import { SPEAKERS, DEFAULT_SPEAKER } from "./constants";

const App = () => {
  // Model loading
  const [ready, setReady] = useState(null);
  const [disabled, setDisabled] = useState(false);
  const [progressItems, setProgressItems] = useState([]);

  // Inputs and outputs
  const [text, setText] = useState("I love Hugging Face!");
  const [selectedSpeaker, setSelectedSpeaker] = useState(DEFAULT_SPEAKER);
  const [output, setOutput] = useState(null);

  // Create a reference to the worker object.
  const worker = useRef(null);

  // We use the `useEffect` hook to setup the worker as soon as the `App` component is mounted.
  useEffect(() => {
    if (!worker.current) {
      // Create the worker if it does not yet exist.
      worker.current = new Worker(new URL("./worker.js", import.meta.url), {
        type: "module",
      });
    }

    // Create a callback function for messages from the worker thread.
    const onMessageReceived = (e) => {
      switch (e.data.status) {
        case "initiate":
          // Model file start load: add a new progress item to the list.
          setReady(false);
          setProgressItems((prev) => [...prev, e.data]);
          break;

        case "progress":
          // Model file progress: update one of the progress items.
          setProgressItems((prev) =>
            prev.map((item) => {
              if (item.file === e.data.file) {
                return { ...item, progress: e.data.progress };
              }
              return item;
            }),
          );
          break;

        case "done":
          // Model file loaded: remove the progress item from the list.
          setProgressItems((prev) =>
            prev.filter((item) => item.file !== e.data.file),
          );
          break;

        case "ready":
          // Pipeline ready: the worker is ready to accept messages.
          setReady(true);
          break;

        case "complete":
          // Generation complete: re-enable the "Translate" button
          setDisabled(false);

          const blobUrl = URL.createObjectURL(e.data.output);
          setOutput(blobUrl);
          break;
      }
    };

    // Attach the callback function as an event listener.
    worker.current.addEventListener("message", onMessageReceived);

    // Define a cleanup function for when the component is unmounted.
    return () =>
      worker.current.removeEventListener("message", onMessageReceived);
  });

  const handleGenerateSpeech = () => {
    setDisabled(true);
    worker.current.postMessage({
      text,
      speaker_id: selectedSpeaker,
    });
  };

  const isLoading = ready === false;
  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100">
      <div
        className="absolute gap-1 z-50 top-0 left-0 w-full h-full transition-all px-8 flex flex-col justify-center text-center"
        style={{
          opacity: isLoading ? 1 : 0,
          pointerEvents: isLoading ? "all" : "none",
          background: "rgba(0, 0, 0, 0.9)",
          backdropFilter: "blur(8px)",
        }}
      >
        {isLoading && (
          <label className="text-white text-xl p-3">
            Loading models... (only run once)
          </label>
        )}
        {progressItems.map((data) => (
          <div key={`${data.name}/${data.file}`}>
            <Progress
              text={`${data.name}/${data.file}`}
              percentage={data.progress}
            />
          </div>
        ))}
      </div>
      <div className="bg-white p-8 rounded-lg shadow-lg w-full max-w-xl m-2">
        <h1 className="text-3xl font-semibold text-gray-800 mb-1 text-center">
          In-browser Text to Speech
        </h1>
        <h2 className="text-base font-medium text-gray-700 mb-2 text-center">
          Made with{" "}
          <a
            href="https://huggingface.co/docs/transformers.js"
            target="_blank"
            rel="noreferrer"
          >
            🤗 Transformers.js
          </a>
        </h2>
        <div className="mb-4">
          <label
            htmlFor="text"
            className="block text-sm font-medium text-gray-600"
          >
            Text
          </label>
          <textarea
            id="text"
            className="border border-gray-300 rounded-md p-2 w-full"
            rows="4"
            placeholder="Enter text here"
            value={text}
            onChange={(e) => setText(e.target.value)}
          ></textarea>
        </div>
        <div className="mb-4">
          <label
            htmlFor="speaker"
            className="block text-sm font-medium text-gray-600"
          >
            Speaker
          </label>
          <select
            id="speaker"
            className="border border-gray-300 rounded-md p-2 w-full"
            value={selectedSpeaker}
            onChange={(e) => setSelectedSpeaker(e.target.value)}
          >
            {Object.entries(SPEAKERS).map(([key, value]) => (
              <option key={key} value={value}>
                {key}
              </option>
            ))}
          </select>
        </div>
        <div className="flex justify-center">
          <button
            className={`${
              disabled
                ? "bg-gray-400 cursor-not-allowed"
                : "bg-blue-500 cursor-pointer hover:bg-blue-600"
            } text-white rounded-md py-2 px-4`}
            onClick={handleGenerateSpeech}
            disabled={disabled}
          >
            {disabled ? "Generating..." : "Generate"}
          </button>
        </div>
        {output && <AudioPlayer audioUrl={output} mimeType="audio/wav" />}
      </div>
    </div>
  );
};

export default App;
